apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/BlackBird-Coding/mc-k8s.git'
    targetRevision: HEAD
    path: apps
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: minecraft
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true